# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./custom-constraint-templates
- ./RBAC
- ./network
- ./resource-provision

patches: 
- target:
    name: tls-enforced-enabled-destination-rule
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: default-role-disallow-edit-endpoint
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: block-process-namespace-sharing
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: anonymous-unauthenticated-system-disallow-role-association
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: service-allowed-external-ips
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: disallow-external-service-gateway
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: service-disallow-load-balancer
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: service-disallow-node-port
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: auth-policy-disallow-all-source-principals
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: disallowed-subjects-for-rolebinding
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
- target:
    name: container-image-restricted-repos
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny